const documents = [
  {
    ref: 'FAC-00001',
    date: '14-01-2023',
    beneficiaire: { nom: 'Anis Zahrouni', avatar: '300-4.jpg' },
    status: { label: 'Nouveaux', style: 'red' },
    type: 'Facture',
    totalTTC: '4796',
  },
  {
    ref: 'BON-00015',
    date: '19-01-2023',
    beneficiaire: { nom: 'Ahmed Zahrouni', avatar: '300-7.jpg' },
    status: { label: 'Payées', style: 'blue' },
    type: 'Bon de livraison',
    totalTTC: '84160',
  },
  {
    ref: 'DEV-00027',
    date: '22-01-2023',
    beneficiaire: { nom: 'Emma Thompson', avatar: '300-5.jpg' },
    status: { label: 'En attente', style: 'orange' },
    type: 'Devis',
    totalTTC: '3200',
  },
  {
    ref: 'CMD-00042',
    date: '28-01-2023',
    beneficiaire: { nom: 'John Smith', avatar: '300-2.jpg' },
    status: { label: 'Validée', style: 'green' },
    type: 'Commande',
    totalTTC: '13500',
  },
  {
    ref: 'FAC-00003',
    date: '03-02-2023',
    beneficiaire: { nom: 'Sophia Martinez', avatar: '300-7.jpg' },
    status: { label: 'Nouveaux', style: 'red' },
    type: 'Facture',
    totalTTC: '9850',
  },
  {
    ref: 'BON-00018',
    date: '09-02-2023',
    beneficiaire: { nom: 'Oliver Garcia', avatar: '300-8.jpg' },
    status: { label: 'En cours', style: 'yellow' },
    type: 'Bon de livraison',
    totalTTC: '62540',
  },
  {
    ref: 'DEV-00031',
    date: '14-02-2023',
    beneficiaire: { nom: 'Emily Davis', avatar: '300-3.jpg' },
    status: { label: 'Refusé', style: 'gray' },
    type: 'Devis',
    totalTTC: '4500',
  },
  {
    ref: 'CMD-00047',
    date: '21-02-2023',
    beneficiaire: { nom: 'William Clark', avatar: '300-10.jpg' },
    status: { label: 'En cours', style: 'yellow' },
    type: 'Commande',
    totalTTC: '76000',
  },
  {
    ref: 'FAC-00005',
    date: '26-02-2023',
    beneficiaire: { nom: 'Ava Robinson', avatar: '300-9.jpg' },
    status: { label: 'Payées', style: 'blue' },
    type: 'Facture',
    totalTTC: '2860',
  },
  {
    ref: 'BON-00021',
    date: '02-03-2023',
    beneficiaire: { nom: 'Daniel Wilson', avatar: '300-6.jpg' },
    status: { label: 'Nouveaux', style: 'red' },
    type: 'Bon de livraison',
    totalTTC: '9400',
  },
  {
    ref: 'DEV-00036',
    date: '08-03-2023',
    beneficiaire: { nom: 'Sarah Johnson', avatar: '300-1.jpg' },
    status: { label: 'En attente', style: 'orange' },
    type: 'Devis',
    totalTTC: '1800',
  },
  {
    ref: 'CMD-00052',
    date: '14-03-2023',
    beneficiaire: { nom: 'Michael Anderson', avatar: '300-4.jpg' },
    status: { label: 'Validée', style: 'green' },
    type: 'Commande',
    totalTTC: '9800',
  },
];

export { documents };
